//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Tablas_relacionadas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int id_Productos { get; set; }
        public string nom_Producto { get; set; }
        public string descrip_Producto { get; set; }
        public int cod_Categoria { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
